COMP: Workaround gtest uninitialized warning / error
Addresses:

[1/5] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
FAILED: googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
/usr/bin/c++  -I/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/include -I/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++11 -MD -MT googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -MF googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -c /home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-all.cc
In file included from /home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-all.cc:42:
/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-death-test.cc:1283:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1283 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-death-test.cc:1273:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1273 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/matt/bin/ITKCleaver-GCC-Release/externals/googletest/src/googletest/googletest/src/gtest-death-test.cc:1281:7: note: ‘dummy’ declared here
 1281 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors

with GCC 11.2.0